currencies:
  datasets:
    eurusd:
      db_file: 'currency_data.db'
      frequencies:
        1d:
          raw_table: 'eurusd_1d'
          csv_extract_file: 'eurusd_extract_1d.csv'
          feature_engineering_table: 'eurusd_1d_engineered_features'
